apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-service-2-streams
  namespace: amplify-streams
  labels:
    app: nginx-ingress
spec:
  type: NodePort
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
      nodePort: 30450
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: streams
    app.kubernetes.io/name: nginx-ingress-controller
 